#!/usr/bin/env node

import { Command } from 'commander';
import path from 'path';
import server from 'refaktor-ui';
import { MinIOAdapter } from '../src/file-adapters';
import { getConfig } from '../src/get-config';
import { ImageComparer } from '../src/ImageComparer';
import { logger } from '../src/logger';
import { ScreenshotGenerator } from '../src/ScreenshotGenerator';
import { CliSerializer, FileSerializer } from '../src/serializer';
import { ImageBase64Transformer } from '../src/transformers/ImageBase64Transformer';
import { IScreenshotType } from '../src/types';
import { cleanup } from '../src/utils/cleanup';
import { commandSetup } from '../src/utils/command-setup';
import { getAdapter } from '../src/utils/get-adapter';

const open = import('open');

const program = new Command();

program
.name('refactor')
.description('Generates screenshots and compares them to a later run to ensure the refactoring did not change anything unintended')
.option('-s, --silent', 'be silent')
.option('-v, --verbose', 'be verbose');

program.command('generate')
.option('--config <file>', 'Path to your config file')
.option('--overwrite', 'Generates a new screenshot even if they already exists.')
.description('Generates new screenshots')
.action(async (opts) => {
  commandSetup(program);

  const config = await getConfig(opts.config);
  const generator = new ScreenshotGenerator();
  const adapter = getAdapter(config);
  generator.setFileAdapter(adapter);
  await generator.takeScreenshots(config, opts.overwrite ?? false, IScreenshotType.ORIGINAL);

});

program.command('compare')
.option('--config <file>', 'Path to the config .js')
.option('--out <file>', 'Only executes the command for a given config id')
.option('--cli', 'Prints the result in a table in the CLI')
.option('--base64', 'Inline the images as base64 data')
.option('--open', 'Open the folder with the results after the command finished')
.option('--ui', 'Inspect the result in browser UI')
.description('Takes new screenshots and compares them to the already created ones')
.action(async (opts) => {
  commandSetup(program);

  const config = await getConfig(opts.config);

  const generator = new ScreenshotGenerator();
  const comparer = new ImageComparer();
  const adapter = getAdapter(config);
  generator.setFileAdapter(adapter);
  comparer.setFileAdapter(adapter);

  await generator.takeScreenshots(config, true, IScreenshotType.COMPARE);

  const result = await comparer.compare(config);
  if (opts.base64 || opts.ui) {
    result.addTransformer(new ImageBase64Transformer(adapter, config));
  }

  const transformed = await result.transform();

  if (opts.cli) {
    const cliSerializer = new CliSerializer();
    await cliSerializer.serialize(transformed);
  }

  if (opts.out) {
    const fileSerializer = new FileSerializer(opts.out);
    await fileSerializer.serialize(transformed);
  }

  if (opts.open) {
    await (await open).default('./');
  }

  if (opts.ui) {
    server(transformed);
    await (await open).default('http://localhost:3000');
    logger.info('Serving UI @ http://localhost:3000');
  }
});


program.command('inspect')
.argument('file', 'Path to the config .js')
.description('Opens up the UI to inspect a json file generated by the compare command')
.action(async (file) => {
  const results = require(path.resolve(process.cwd(), file));
  server(results);
  logger.info('Serving UI @ http://localhost:3000');
  await (await open).default('http://localhost:3000');
});

program.command('cleanup')
.argument('config', 'Path to the config .js')
.description('Remove unused screenshots')
.action(async (pagesPath, opts) => {
  commandSetup(program);
  const configs = await getConfig(pagesPath);
  await cleanup(configs);
});

program.parse();
