export * from './ICompareResult'
export * from './IPagesConfig'
export * from './IPagesEntry'
export * from './IScreenshotOutputConfig'
export * from './IScreenshotType'
export * from './ISerializedResult'
export * from './ITransformer'